---
name: Match files

on:  # yamllint disable-line rule:truthy
  push:
    branches: ['release-2.0']

jobs:
  build:
    name: Match files
    runs-on: ['ubuntu-latest']

    steps:
      - uses: actions/checkout@v2

      - name: Glob match
        uses: tj-actions/glob@v16
        id: glob
        with:
          files: |
            public/**/*

      - name: Show all matching files
        run: |
          echo "${{ steps.glob.outputs.paths }}"

      - name:  Remove file
        run: |
          rm -rf public/base/css/other.css
          touch public/base/css/something.css

      # This step will evaluate the repo status and report the changes
      - name: Get changed files in the public folder
        id: changes
        uses: tj-actions/verify-changed-files@v12
        with:
          files: |
            public/**/*
          # separator: "\r\n"

      - name: Run step if any file(s) in the public folder changed
        # if: steps.changes.outputs.files_changed == 'true'
        run: |
          printf "Changed files: ${{ steps.changes.outputs.changed_files }}"

